### ISSUE TITLE
Solana quickstart flow should have its own tooling options

### ISSUE THREAD

**Issue by thatguyintech** [alchemyplatform/create-web3-dapp#25]
Currently, the dapp wizard has the same flow for EVM vs. Solana projects. We should add Solana-specific flow.

```bash
🔵 Welcome to the create-web3-dapp wizard 🔵


✔ Please, insert a project name … solana-dapp
solana-dapp
✔ For which VM are you building for? › Solana
✔ Do you want to import the template files? … no / yes
✔ Do you want to import a Blockchain Development environment? … no / yes
? Choose a Blockchain development environment › - Use arrow-keys. Return to submit.
❯   Hardhat
    Foundry
```

<img width="855" alt="Screen Shot 2022-08-09 at 12 52 02 PM" src="https://user-images.githubusercontent.com/3393523/183749208-43f276ae-c50e-4346-bfd0-9c97bc4ca4ef.png">

**Comment by Eversmile12** [comment]
Can confirm this is only momentarily while we wait to actually have solana tools in place! There's an if blocking it at the moment

We can love forward unlocking it!

**Comment by Eversmile12** [comment]
Solved!
