### ISSUE TITLE
Adding a simple animation to Alchemy Logo

### ISSUE THREAD

**Issue by dicethedev** [alchemyplatform/create-web3-dapp#28]
![alchemy](https://user-images.githubusercontent.com/85754527/183903010-5b717474-da02-41b4-a19d-5800d9735071.png)

@Eversmile12 is it possible to add a simple animation to this Logo? if possible let me add animation to the logo.

**Comment by Eversmile12** [comment]
Yes! Please go on @dicethedev

**Comment by dicethedev** [comment]
@Eversmile12 where can I get access to the file? I cannot see it bro.
