### ISSUE TITLE
[ENHANCEMENT] Implement Linting and automate Testing on Pull Request

### ISSUE THREAD

**Issue by Eversmile12** [alchemyplatform/create-web3-dapp#43]
Would be cool to have all code linted and tested when a new PR is sent.

**Comment by butovsky** [comment]
related to #23, I guess
@Eversmile12 I can implement a simple .yml script that does the job.

the question is whether we need such checks on every pr (including e.g. bugfix -> 1.2 commit) or only on main and on PRs which are to be merged with main
