### ISSUE TITLE
folders delete themselves after installing create-web-3-dapp

### ISSUE THREAD

**Issue by Dvdb91** [alchemyplatform/create-web3-dapp#49]
I tried to install create-web-3-dapp according to guidelines.

As soon as the installation finishes, I can see folders "backend" and "frontend".
Within seconds those folders are deleted again and I am left with an empty folder. 
Didn't click anything.

Anyone a clue what I might be doing wrong?

**Comment by 0xchristiaan** [comment]
I am encountering the same problem, this is also related to issue #50

**Comment by Dvdb91** [comment]
> I am encountering the same problem, this is also related to issue #50

Yes indeed, the terminal output looks the same with me as in #50
