### ISSUE TITLE
Link to the docs for create-web3-dapp results in 404 error

### ISSUE THREAD

**Issue by sclement2** [alchemyplatform/create-web3-dapp#56]
This link -> https://docs.alchemy.com/create-web3-dapp results in a 404 error

**Comment by jgarrettvml** [comment]
I've been receiving the same error on this link, and looking for a corresponding page in the docs for this sample app, but just links back to the repo.

**Comment by adityakode** [comment]
@sclement2   you can use https://www.alchemy.com/dapps/create-web3-dapp.

**Comment by xscottxbrownx** [comment]
@adityakode don't we want to actually link to here: https://docs.alchemy.com/docs/create-web3-dapp

?

**Comment by xscottxbrownx** [comment]
Once PR #62 is reviewed/approved/merged, this issue is solved and can be closed.
