### ISSUE TITLE
NFT explorer has runtime error

### ISSUE THREAD

**Issue by josh0x** [alchemyplatform/create-web3-dapp#66]
Followed this 2 min tutorial from Alchemy's [Youtube](https://www.youtube.com/watch?v=r3DP64sg8Mo&ab_channel=Alchemy)
Message in terminal: 

error - ./pages/_app.js:5:0
Module not found: Can't resolve 'wagmi'
  3 | 
  4 | import { getDefaultWallets, RainbowKitProvider } from "@rainbow-me/rainbowkit";
> 5 | import { configureChains, createClient, WagmiConfig } from "wagmi";
  6 | import {
  7 |   mainnet,
  8 |   polygon,

**Comment by Eversmile12** [comment]
Solved adding wagmi to default dependencies
