### ISSUE TITLE
[BUG] Discord link not being an absolute link in contributing.md leads to 404 error

### ISSUE THREAD

**Issue by 0xdevant** [alchemyplatform/create-web3-dapp#68]
As stated, the discord link in contributing.md is leading to a wrong site since it's just written as a relative link, it should be fixed to an absolute link:
https://alchemy.com/discord

**Comment by xscottxbrownx** [comment]
There are two PR's now for this:

#69 and #70 

honestly the link works for me as is, 🤷🏻‍♂️

**Comment by 0xdevant** [comment]
The discord link that wasn't working previously was at the end of the file, maybe you overlooked it.

Anyway my PR has been merged so I will close this issue here.
