### ISSUE TITLE
Upgrade Git ignore

### ISSUE THREAD

**Issue by Ankush263** [alchemyplatform/create-web3-dapp#77]
Currently, the .gitignore files only contain .env.local. It would be great if ***node-modules*** & ***package-lock.json*** had also been added here.

**Comment by 0xRowdy** [comment]
I created the same issue. #74

**Comment by Eversmile12** [comment]
Updated in the latest commit - PR was giving me errors @Ankush263 

https://github.com/alchemyplatform/create-web3-dapp/commit/f7bdcad2af139e36f380af963df96ab60c8cfbce
