### ISSUE TITLE
Three errors when installing latest version of create-web3-dapp

### ISSUE THREAD

**Issue by jlin27** [alchemyplatform/create-web3-dapp#95]
**Describe the bug**
When following the directions in the [Quick Start](https://github.com/alchemyplatform/create-web3-dapp#quick-start), I get the following three errors on a fresh install:

1. After creating a new app, I get `Error: ENOENT: no such file or directory, mkdir 'pages/api'`
<img width="751" alt="image" src="https://github.com/alchemyplatform/create-web3-dapp/assets/8042156/f5e67ce6-e801-401d-a735-323a2a3ef65e">

2. After the app is created, and I run `npm run dev`,  I get

```
Error: > The `app` directory is experimental. To enable, add `appDir: true` to your `next.config.js` configuration under `experimental`. See https://nextjs.org/docs/messages/experimental-app-dir-config
```

<img width="1036" alt="image" src="https://github.com/alchemyplatform/create-web3-dapp/assets/8042156/e34e4768-5507-42f5-9bf5-162d7991c22b">
 
 I can move past this by updating `next.config.js` to 
 ```
 /** @type {import('next').NextConfig} */

module.exports = {
  reactStrictMode: false,
  webpack: (config) => {
    config.resolve.fallback = { fs: false, net: false };
    return config;
  },
  experimental: { appDir: true },
};
```
3. If I run `npm run dev` again, I get the following the in browser: 
<img width="1039" alt="image" src="https://github.com/alchemyplatform/create-web3-dapp/assets/8042156/43d02e25-6c7d-4a9d-afce-0b825ba2851e">
and this in the terminal: 
<img width="778" alt="image" src="https://github.com/alchemyplatform/create-web3-dapp/assets/8042156/2831e723-93ae-43c7-bfe2-2960b46818ba">

**To Reproduce**
1.  Run `npx create-web3-dapp@latest`
2. Choose how to start: › Create default full-stack dapp
3. Choose your chain › Polygon
5. Do you already have an Alchemy account yes
6. Insert your Alchemy API Key
7. Get `Error: ENOENT: no such file or directory, mkdir 'pages/api'`
8. Run `cd my-create-web3-dapp && npm run dev`
9. Get `Error: > The `app` directory is experimental. To enable, add `appDir: true` to your `next.config.js` configuration under `experimental`.`

**Expected behavior**
Expect no errors when installing fresh version of the dapp

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome

**Comment by Eversmile12** [comment]
This should be solved in v 3.0!
